import Head from 'next/head';
import styles from '../styles/Home.module.css';

import LandingOne from '../components/LandingOne';
import LandingTwo from '../components/LandingTwo';
import LandingThree from '../components/LandingThree';
import LandingFive from '../components/LandingFive';
import LandingSeven from '../components/LandingSeven';
import LandingSix from '../components/LandingSix';
import landingPages from '../public/assets/data/landingPages';
import LandingFour from '../components/LandingFour';
import Layout from './Layout';

export default function Home() {
  return (
    <Layout navbarType={1}>
      <div className={styles.container}>
        <Head>
          <title>Agreeculture Clone</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <LandingOne
          textOne={landingPages.landingOne.textOne}
          textTwo={landingPages.landingOne.textTwo}
          images={landingPages.landingOne.images}
        />
        <LandingTwo
          textOne={landingPages.landingTwo.textOne}
          textTwo={landingPages.landingTwo.textTwo}
          images={landingPages.landingTwo.images}
        />
        <LandingThree data={landingPages.landingThree} />
        <LandingFour data={landingPages.dataTestimoni1} />

        <LandingFive data={landingPages.landingFive} />
        <LandingSeven data={landingPages.daftarBerita} />
        <LandingSix
          text1='Kembangkan bisnis pertanian Anda,'
          text2='tumbuh dengan pesat bersama Agree'
          text3='Saya Tertarik'
          background='#47AF64'
        />
      </div>
    </Layout>
  );
}
